// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.arago.tracking;

public interface TrackAdImpressionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracking.TrackAdImpressionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string adId = 1;</code>
   */
  java.lang.String getAdId();
  /**
   * <code>string adId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAdIdBytes();
}
