// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.arago.tracking;

public final class Tracking {
  private Tracking() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tracking_TrackAdImpressionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tracking_TrackAdImpressionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tracking_TrackAdImpressionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tracking_TrackAdImpressionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016tracking.proto\022\010tracking\"(\n\030TrackAdImp" +
      "ressionRequest\022\014\n\004adId\030\001 \001(\t\"=\n\031TrackAdI" +
      "mpressionResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007me" +
      "ssage\030\002 \001(\t2o\n\017TrackingService\022\\\n\021TrackA" +
      "dImpression\022\".tracking.TrackAdImpression" +
      "Request\032#.tracking.TrackAdImpressionResp" +
      "onseB\026\n\022com.arago.trackingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tracking_TrackAdImpressionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tracking_TrackAdImpressionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tracking_TrackAdImpressionRequest_descriptor,
        new java.lang.String[] { "AdId", });
    internal_static_tracking_TrackAdImpressionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tracking_TrackAdImpressionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tracking_TrackAdImpressionResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
